export type Place = {
    id: number;
    companyName: string;
    companyLogo: string;
    category: string;
    address: string;
    city: string;
    subdistrict: string;
    workTypes: string[];
    openPositions: number;
    activeInterns: number;
    totalAlumni: number;
    isVerified: boolean;
    description?: string;
};

export const PLACES_DUMMY: Place[] = [
    {
        id: 1,
        companyName: "Glints",
        companyLogo: "/gambar1.png",
        category: "Perusahaan Digital Creative",
        address: "Menara Standard Chartered, Jl. Prof. Dr. Satrio",
        city: "Jakarta Selatan",
        subdistrict: "Setiabudi",
        workTypes: ["Hybrid", "Onsite"],
        openPositions: 1,
        activeInterns: 15,
        totalAlumni: 120,
        isVerified: true,
        description: "Glints adalah salah satu platform rekrutmen terbesar di Asia Tenggara yang membantu para profesional muda dalam mengembangkan karir mereka.",
    },
    {
        id: 2,
        companyName: "Tokopedia",
        companyLogo: "/gambar2.png",
        category: "Perusahaan E-Commerce",
        address: "Ciputra World 2, Jl. Prof. Dr. Satrio",
        city: "Jakarta Selatan",
        subdistrict: "Setiabudi",
        workTypes: ["Hybrid", "Onsite"],
        openPositions: 1,
        activeInterns: 45,
        totalAlumni: 500,
        isVerified: true,
        description: "Tokopedia adalah perusahaan teknologi Indonesia dengan misi mencapai pemerataan ekonomi secara digital.",
    },
    {
        id: 3,
        companyName: "Gojek",
        companyLogo: "/gambar3.png",
        category: "Perusahaan Fintech",
        address: "Pasaraya Blok M Gedung B, Jl. Iskandarsyah II",
        city: "Jakarta Selatan",
        subdistrict: "Kebayoran Baru",
        workTypes: ["Hybrid", "Remote", "Onsite"],
        openPositions: 2,
        activeInterns: 60,
        totalAlumni: 850,
        isVerified: true,
        description: "Gojek adalah perusahaan teknologi asal Indonesia yang melayani angkutan melalui jasa ojek.",
    },
    {
        id: 4,
        companyName: "Bukalapak",
        companyLogo: "/gambar5.png",
        category: "Perusahaan E-Commerce",
        address: "Jl. R.A. Kartini No.Kav. 14, Cilandak",
        city: "Jakarta Selatan",
        subdistrict: "Cilandak",
        workTypes: ["Remote", "Hybrid"],
        openPositions: 1,
        activeInterns: 30,
        totalAlumni: 400,
        isVerified: true,
        description: "Bukalapak adalah salah satu marketplace terbesar di Indonesia yang memberdayakan UMKM.",
    },
    {
        id: 5,
        companyName: "Shopee",
        companyLogo: "/shopee.png",
        category: "Perusahaan E-Commerce (Beauty)",
        address: "Jakarta Selatan",
        city: "Jakarta",
        subdistrict: "Jakarta",
        workTypes: ["Hybrid"],
        openPositions: 1,
        activeInterns: 25,
        totalAlumni: 300,
        isVerified: true,
        description: "Shopee adalah platform e-commerce terdepan di Asia Tenggara dan Taiwan.",
    },
    {
        id: 6,
        companyName: "Traveloka",
        companyLogo: "/traveloka.png",
        category: "Perusahaan F&B",
        address: "Tangerang",
        city: "Tangerang",
        subdistrict: "Tangerang",
        workTypes: ["Onsite"],
        openPositions: 1,
        activeInterns: 20,
        totalAlumni: 250,
        isVerified: true,
        description: "Traveloka adalah perusahaan teknologi terkemuka di Asia Tenggara yang menyediakan berbagai kebutuhan perjalanan.",
    },
    {
        id: 7,
        companyName: "PLN",
        companyLogo: "/pln.png",
        category: "BUMN (Energi)",
        address: "Jakarta Pusat",
        city: "Jakarta Pusat",
        subdistrict: "Menteng",
        workTypes: ["Onsite"],
        openPositions: 3,
        activeInterns: 50,
        totalAlumni: 600,
        isVerified: true,
        description: "PT PLN (Persero) adalah Badan Usaha Milik Negara yang bergerak di bidang ketenagalistrikan.",
    },
    {
        id: 8,
        companyName: "Garuda Indonesia",
        companyLogo: "/garuda.png",
        category: "BUMN (Penerbangan)",
        address: "Jakarta Pusat",
        city: "Jakarta Pusat",
        subdistrict: "Kemayoran",
        workTypes: ["Onsite"],
        openPositions: 2,
        activeInterns: 30,
        totalAlumni: 450,
        isVerified: true,
        description: "Garuda Indonesia adalah maskapai penerbangan nasional Indonesia.",
    },
    {
        id: 9,
        companyName: "Telkom Indonesia",
        companyLogo: "/smktelkom.png",
        category: "BUMN (Telekomunikasi)",
        address: "Bandung",
        city: "Bandung",
        subdistrict: "Coblong",
        workTypes: ["Hybrid"],
        openPositions: 5,
        activeInterns: 80,
        totalAlumni: 900,
        isVerified: true,
        description: "Telkom Indonesia adalah perusahaan informasi dan komunikasi serta penyedia jasa telekomunikasi terbesar di Indonesia.",
    },
];
